# ===================================================
#                    FRONTEND
# ===================================================

# namespace: shopverse-dev

# ---------------------------------------------------
# Container
# ---------------------------------------------------
image:
  ecr_registry: 254405569649.dkr.ecr.us-east-1.amazonaws.com
  ecr_repository: shopverse-dev/frontend
  tag: v1
  digest: sha256:2661d27fb70640c7bbc2e31f7f0a2f5f4b891f27832de0a284443790aa46db4f
containerName: frontend
imagePullPolicy: Always
terminationGracePeriodSeconds: 30
# ---------------------------------------------------
# Labels
# ---------------------------------------------------
labels:
  app.kubernetes.io/name: shopverse
  app.kubernetes.io/component: frontend
  app.kubernetes.io/env: dev
  app.kubernetes.io/version: 1.0.0
# ---------------------------------------------------
# Deployment
# ---------------------------------------------------
deployment:
  name: frontend-deploy
  replicas: 1
# ---------------------------------------------------
# Service
# ---------------------------------------------------  
service:
  name: frontend-svc
  type: ClusterIP
  port: 8080
  targetPort: 8080
# ---------------------------------------------------
# Pod Annotations
# ---------------------------------------------------
annotations:
  enabled: false
  enable_checksum: false
  checksum_file: configmap.yaml
  values: {}
  # checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  # reloader.stakater.com/auto: "true"
# ---------------------------------------------------
# Security Context
# ---------------------------------------------------
podSecurityContext:
  enabled: true
  values:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
containerSecurityContext:
  enabled: true
  values:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 101 # nginx user 101
# ---------------------------------------------------
# Volumes and Volume Mounts
# ---------------------------------------------------
volumes:
  enabled: true
  values:
    - name: nginx-run
      emptyDir: {}
    - name: nginx-cache
      emptyDir: {}
volumeMounts:
  enabled: true
  values:
    - name: nginx-run
      mountPath: /run
    - name: nginx-cache
      mountPath: /var/cache/nginx
# ---------------------------------------------------
# Configmaps & Secrets
# ---------------------------------------------------
configmap:
  enabled: false
  name: frontend-configmap
  values:
    DB_HOST: ""
    DB_PORT: "3306"
    DB_NAME: "shopverse"
    FRONTEND_ORIGIN: "*"
secret:
  name: db-credentials
  create: false # Creates through ESO
envFrom:
  enabled: false
  values:
    - configMapRef:
        name: frontend-configmap
    - secretRef:
        name: db-credentials # Creates through ESO   
# ---------------------------------------------------
# Limits & Requests
# ---------------------------------------------------
resources:
  enabled: true
  values:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
# ---------------------------------------------------
# Healthcheck Probes
# ---------------------------------------------------
startupProbe:
  enabled: true
  values:
    httpGet:
      path: /health
      port: 8080
    failureThreshold: 10
    periodSeconds: 10
readinessProbe:
  enabled: true
  values:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
livenessProbe:
  enabled: true
  values:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 30
# ---------------------------------------------------
# Autoscaling
# ---------------------------------------------------
autoscaling:
  enabled: false
  values:
    name: frontend-hpa
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
# ---------------------------------------------------
# Service Account
# ---------------------------------------------------
serviceAccount:
  create: false
  values:
    name: frontend-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/frontend-role
# ---------------------------------------------------
# Target Group Binding
# ---------------------------------------------------
targetGroupBinding:
  enabled: true
  name: shopverse-dev-frontend-tgb
  values:
    targetType: "ip"
    targetGroupName: shopverse-dev-frontend-tg
    # targetGroupARN: "REPLACE_WITH_TERRAFORM_OUTPUT"
